server:
  port: 9000
  servlet:
    context-path: "/api/v1"

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/nnpia
    username: nnpia
    password: nnpia